# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[titles]
Note = 'Nota'
PrimitiveNode = 'Nodo primitivo'
Reroute = 'Cambiare la rotta di'
Sampler = 'Imparaticcio'
SamplerAdvanced = 'Campionatore avanzato'
CheckpointLoaderSimple = 'Caricatore Checkpoint Semplice'
VAELoader = 'Caricatore VAE'
LoraLoader = 'Caricatore Lora'
ControlNetLoader = 'Caricatore ControlNet'
DiffControlNetLoader = 'Caricatore DiffControlNet'
StyleModelLoader = 'Stile Modello Caricatore'
CLIPVisionLoader = 'Caricatore di visione CLIP'
unCLIPCheckpointLoader = 'Caricatore di checkpoint unCLIP'
GLIGENLoader = 'Caricatore GLIGEN'
UpscaleModelLoader = 'Caricatore modello di lusso'
HypernetworkLoader = 'Caricatore Hypernetwork'
StyleModelApply = 'Modello di stile Applica'
GLIGENTextBoxApply = 'Si Applica La Casella Di Testo GLIGEN'
CLIPTextEncode = 'Codifica testo CLIP'
CLIPSetLastLayer = "CLIP Imposta l'ultimo strato"
ConditioningAverage = 'Condizionamento medio'
ConditioningCombine = 'Combinazione di condizionamento'
ConditioningConcat = 'Condizionamento Concat'
ConditioningSetArea = 'Area Set Di Condizionamento'
ConditioningSetAreaPercentage = "Condizionamento Imposta La Percentuale Dell'area"
ConditioningSetMask = 'Set di condizionamento Maschera'
CLIPVisionEncode = 'Codifica Visione CLIP'
unCLIPConditioning = 'unCLIP Condizionamento'
ControlNetApply = 'ControlNet Applica'
ControlNetApplyAdvanced = 'ControlNet Applica Avanzato'
VAEEncodeForInpaint = 'Codifica VAE Per Inpaint'
SetLatentNoiseMask = 'Imposta una maschera antirumore latente'
LatentFromBatch = 'Latente dal lotto'
RepeatLatentBatch = 'Ripeti il lotto latente'
RebatchLatents = 'Rebatch latenti'
LatentRotate = 'Ruota latente'
LatentFlip = 'Flip latente'
LatentCrop = 'Coltura latente'
VAEDecode = 'VAE Decodifica'
VAEEncode = 'Codifica VAE'
EmptyLatentImage = 'Immagine latente vuota'
LatentUpscale = 'Lusso latente'
LatentUpscaleBy = 'Upscale latente di'
LatentComposite = 'Composito latente'
LatentCompositeMasked = 'Composito latente mascherato'
ImageScale = "Scala dell'immagine"
ImageScaleBy = "Scala Dell'immagine Di"
ImageUpscaleWithModel = 'Immagine Di Lusso Con Modello'
ImageScaleToTotalPixels = "Scala Dell'immagine Ai Pixel Totali"
ImageBlend = 'Miscela di immagini'
ImageBlur = "Sfocatura dell'immagine"
ImageQuantize = "Quantizza l'immagine"
ImageSharpen = 'Nitidezza immagine'
Canny = 'Cauto'
SaveImage = 'Salva immagine'
PreviewImage = 'Anteprima immagine'
LoadImage = 'Carica immagine'
ImageInvert = 'Immagine inverti'
ImageBatch = 'Lotto di immagini'
ImagePadForOutpaint = 'Tampone immagine per Outpaint'
EmptyImage = 'Immagine vuota'
ImageCompositeMasked = 'Immagine Composita Mascherata'
LoadImageMask = 'Carica maschera immagine'
MaskToImage = "Maschera All'immagine"
ImageToMask = 'Immagine Da Mascherare'
ImageColorToMask = "Colore Dell'immagine Da Mascherare"
SolidMask = 'Maschera solida'
InvertMask = 'Inverti la maschera'
CropMask = 'Maschera per il raccolto'
MaskComposite = 'Maschera Composita'
FeatherMask= 'Maschera di piume'
GrowMask = 'Coltiva la maschera'
VAEDecodeTiled = 'VAE Decodifica Piastrellato'
VAEEncodeTiled = 'Codifica VAE Piastrellato'
TomePatchModel = 'Modello di patch Tomo'
SaveLatent = 'Salva latente'
LoadLatent = 'Carico latente'
LatentBlend = 'Miscela latente'
DiffusersLoader = 'Caricatore di diffusori'
CLIPLoader = 'Caricatore CLIP'
CheckpointLoader = 'Caricatore Checkpoint'
UNETLoader = 'Caricatore UNET'
DualCLIPLoader = 'Caricatore Dual CLIP'
ConditioningZeroOut = 'Condizionamento Zero Out'
ConditioningSetTimestepRange = "Impostazione Imposta l'intervallo Timestep"
CLIPTextEncodeSDXL = 'Codifica testo CLIP SDXL'
CLIPTextEncodeSDXLRefiner = 'CLIP Text Encode SDXL Refiner'
ModelMergeSimple = 'Modello Unisci Semplice'
ModelMergeBlocs = 'Modello Unisci Blocchi'
CheckpointSave = 'Checkpoint Salva'
CLIPMergeSimple = 'CLIP Unisci Semplice'
ModelMergeBlockNumber = 'Modello Unisci il numero di blocco'
ModelMergeSDXL = 'Modello Unisci SDXL'
ModelMergeSDXLTransformers = 'Modello Unisci trasformatori SDXL'
ModelMergeSDXLDetailedTransformers = 'Modello Unisci trasformatori dettagliati SDXL'