# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[titles]
Note = "Nota"
PrimitiveNode = "Nodo primitivo"
Reroute = "Reindirizza"
Sampler = "Campionatore"
SamplerAdvanced = "Campionatore avanzato"
CheckpointLoaderSimple = "Checkpoint Loader Semplice"
VAELoader = "Caricatore VAE"
LoraLoader = "Caricatore Lora"
ControlNetLoader = "Caricatore ControlNet"
DiffControlNetLoader = "Caricatore DiffControlNet"
StyleModelLoader = "Stile Modello Loader"
CLIPVisionLoader = "Caricatore di visione CLIP"
unCLIPCheckpointLoader = "unCLIP Caricatore di checkpoint"
GLIGENLoader = "Caricatore GLIGEN"
UpscaleModelLoader = "Caricatore di modelli di lusso"
HypernetworkLoader = "Caricatore iperrete"
StyleModelApply = "Applica modello di stile"
GLIGENTextBoxApply = "Applica casella di testo GLIGEN"
CLIPTextEncode = "CLIP Codifica testo"
CLIPSetLastLayer = "CLIP Imposta ultimo strato"
ConditioningAverage = "Condizionamento medio"
ConditioningCombine = "Condizionamento Combina"
ConditioningConcat = "Condizionamento Concat"
ConditioningSetArea = "Area Set Condizionamento"
ConditioningSetAreaPercentage = "Percentuale area impostata condizionamento"
ConditioningSetMask = "Maschera Set di condizionamento"
CLIPVisionEncode = "Codifica visione CLIP"
unCLIPConditioning = "unCLIP Condizionamento"
ControlNetApply = "Applica ControlNet"
ControlNetApplyAdvanced = "ControlNet Apply Advanced"
VAEEncodeForInpaint = "Codifica VAE per Inpaint"
SetLatentNoiseMask = "Imposta maschera rumore latente"
LatentFromBatch = "Latente da Batch"
RepeatLatentBatch = "Ripeti batch latente"
RebatchLatents = "Rebatch latenti"
LatentRotate = "Rotazione latente"
LatentFlip = "Capovolgimento latente"
LatentCrop = "Raccolto latente"
VAEDecode = "Decodifica VAE"
VAEEncode = "Codifica VAE"
EmptyLatentImage = "Immagine latente vuota"
LatentUpscale = "Latente di alto livello"
LatentUpscaleBy = "Latente di alto livello di"
LatentComposite = "Composito latente"
LatentCompositeMasked = "Composito latente mascherato"
ImageScale = "Scala immagine"
ImageScaleBy = "Scala immagine per"
ImageUpscaleWithModel = "Immagine di ingrandimento con modello"
ImageScaleToTotalPixels = "Scala immagine in pixel totali"
ImageBlend = "Fusione immagini"
ImageBlur = "Sfocatura immagine"
ImageQuantize = "Quantizzazione immagine"
ImageSharpen = "Nitidezza immagine"
Canny = "Astuto"
SaveImage = "Salva immagine"
PreviewImage = "Anteprima immagine"
LoadImage = "Carica immagine"
ImageInvert = "Inverti immagine"
ImageBatch = "Batch di immagini"
ImagePadForOutpaint = "Pad immagine per Outpaint"
EmptyImage = "Immagine vuota"
ImageCompositeMasked = "Immagine Composita Mascherata"
LoadImageMask = "Carica maschera immagine"
MaskToImage = "Maschera Su Immagine"
ImageToMask = "Immagine da mascherare"
ImageColorToMask = "Colore immagine su maschera"
SolidMask = "Maschera solida"
InvertMask = "Inverti maschera"
CropMask = "Maschera di ritaglio"
MaskComposite = "Maschera composita"
FeatherMask= "Maschera di piume"
GrowMask = "Maschera di coltivazione"
VAEDecodeTiled = "Decodifica VAE piastrellata"
VAEEncodeTiled = "Codifica VAE piastrellata"
TomePatchModel = "Modello di toppa tomo"
SaveLatent = "Salva latente"
LoadLatent = "Carico latente"
LatentBlend = "Miscela latente"
DiffusersLoader = "Caricatore diffusori"
CLIPLoader = "Caricatore CLIP"
CheckpointLoader = "Caricatore di checkpoint"
UNETLoader = "UNET Caricatore"
DualCLIPLoader = "Caricatore a doppia clip"
ConditioningZeroOut = "Azzeramento condizionante"
ConditioningSetTimestepRange = "Intervallo di intervalli di tempo impostato per il condizionamento"
CLIPTextEncodeSDXL = "CLIP Codifica testo SDXL"
CLIPTextEncodeSDXLRefiner = "CLIP Testo Codifica SDXL Affinatore"
ModelMergeSimple = "Unisci modello semplice"
ModelMergeBlocs = "Blocchi di fusione del modello"
CheckpointSave = "Salva checkpoint"
CLIPMergeSimple = "CLIP Unisci Semplice"
ModelMergeBlockNumber = "Numero blocco unione modello"
ModelMergeSDXL = "Unisci modello SDXL"
ModelMergeSDXLTransformers = "Modello Unisci Trasformatori SDXL"
ModelMergeSDXLDetailedTransformers = "Model Merge SDXL Detailed Transformers"