# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[main]
utils = "utili"
sampling = "campionamento"
loaders = "caricatori"
conditioning = "condizionamento"
latent = "latente"
image = "immagine"
mask = "maschera"
_for_testing = "per il test"
advanced = "avanzato"
arithmetic = "aritmetica"
model_patches = "patch del modello"
language_model = "modello linguistico"
api = "api"
sd = "sd"
model= "modello"

[common]
samplers = "campionatori"
schedulers = "pianificatori"
sigmas = "sigma"
guiders = "guide"
noise = "rumore"
video_models = "modelli video"
inpaint = "inpaint"
stable_cascade = "cascata stabile"
sd3 = "sd3"
batch = "lotto"
transform = "trasformare"
custom_sampling = "campionamento personalizzato"

[sub_menus]
style_model = "modello di stile"
gligen = "GLIGEN"
instructpix2pix = "instructpix2pix"
upscale_diffusion = "diffusione di alto livello"
3d_models = "Modelli 3d"
upscaling = "ingrandimento"
postprocessing = "post-elaborazione"
preprocessors = "preprocessori"
animation = "animazione"
compositing = "composizione"
attention_experiments = "Esperimenti di attenzione"
audio = "audio"
photomaker = "Fotomaker"
model_merging = "fusione del modello"
model_specific = "specifico per il modello"
cutoff = "taglio"
openapi = "openapi"
