# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[flows]
inputs = 'Ingressi in ingresso'
outputs = 'Uscite in uscita'
widgets = 'Widgets'
	
[values]	
fixed = 'Fisso'
randomize = 'Randomizzare'
increment = 'Aumento'
decrement = 'Decremento'
nearest-exact = 'Più vicino-esatto'
bilinear = 'Bilineare'
area = 'Area'
bislerp = 'Bislerp'
bicubic = 'Bicubico'
enabled = 'Abilitato'
disabled = 'Disabile'
normal = 'Normale'
multiply = 'Moltiplicare'
screen = 'Schermo'
overlay = 'Trasparente'
soft_light = 'Luce soffusa'
none = 'Nessuno'
floyd-steinberg = 'Floyd-steinberg'
bayer-2 = 'Bayer-2'
bayer-4 = 'Bayer-4'
bayer-8 = 'Bayer-8'
bayer-16 = 'Bayer-16'
add = 'Aggiungere'
subtract = 'Sottrarre'
and = 'E'
or = 'O'
xor = 'Xor'
	
[types]	
model = 'Modello'
clip = 'Pinza'
vae = 'Vae'
conditioning = 'Condizionamento'
positive = 'Affermativo'
negative = 'Negativo'
latent = 'Latente'
latent_image = 'Immagine latente'
samples = 'Campioni'
image = 'Immagine'
seed = 'Seme'
steps = 'Passi'
cfg = 'Cfg'
sampler_name = 'Nome del campionatore'
scheduler = 'Schedulatore'
denoise = 'Rumore di denoise'
add_noise = 'Aggiungi rumore'
noise_seed = 'Seme di rumore'
control_after_generate = 'Controllo dopo la generazione'
return_with_leftover_noise = 'Ritorno con rumore residuo'
start_at_step = 'Inizia dal passo'
end_at_step = 'Finisci al passo'
ckpt_name = 'Nome ckpt'
vae_name = 'Vae nome'
pixels = 'Pixels'
mask = 'Maschera'
lora_name = 'Nome lora'
strength_model = 'Modello di forza'
strength_clip = 'Clip di forza'
clip_name = 'Nome clip'
control_net = 'Rete di controllo'
control_net_name = 'Nome della rete di controllo'
clip_vision = 'Visione a clip'
style_model = 'Modello di stile'
style_model_name = 'Nome del modello di stile'
gligen_name = 'Nome gligen'
gligen = 'Gligen'
model_name = 'Nome del modello'
upscale_model = 'Modello di lusso'
hypernetwork_name = "Nome dell'iperrete"
strength = 'Forza'
clip_vision_output = 'Uscita visione clip'
conditioning_to = 'Condizionamento a'
conditioning_from = 'Condizionamento da'
conditioning_to_strength = 'Condizionamento alla forza'
conditioning_1 = 'Condizionamento 1'
conditioning_2 = 'Condizionamento 2'
gligen_textbox_model = 'Modello di casella di testo gligen'
text = 'Testo'
width = 'Larghezza'
height = 'Altezza'
length = 'Lunghezza'
x = 'X'
y = 'Y'
stop_at_clip_layer = 'Fermati al livello della clip'
set_cond_area = "Imposta l'area del cond"
default = 'Inadempienza'
mask_bounds = 'Limiti della maschera'
noise_augmentation = 'Aumento del rumore'
start_percent = 'Inizia in percentuale'
end_percent = 'Fine percentuale'
grow_mask_by = 'Coltiva la maschera di'
batch_index = 'Indice batch'
amount = 'Importo'
batch_size = 'Dimensione del lotto'
rotation = 'Rotazione'
none = 'Nessuno'
ninety_degrees = 'Novanta gradi'
oneeighty_degrees = 'Ottanta gradi'
twoseventy_degrees = 'Duesettanta gradi'
flip_method = 'Metodo flip'
x-axis_vertically = 'Asse x verticalmente'
y-axis_horizontally = 'Asse y orizzontalmente'
upscale_method = 'Metodo di alto livello'
crop = 'Coltura'
scale_by = 'Scala per'
samples_to = 'Campioni a'
samples_from = 'Campioni di'
feather = 'Piuma'
destination = 'Destinazione'
source = 'Fonte'
resize_source = 'Ridimensiona la fonte'
megapixels = 'Megapixel'
image1 = 'Immagine1'
image2 = 'Immagine2'
blend_factor = 'Fattore di fusione'
blend_mode = 'Modalità di fusione'
blur_radius = 'Raggio di sfocatura'
sigma = 'Sigma'
colors = 'Colori'
dither = 'Tergiversare'
sharpen_radius = 'Affila il raggio'
alpha = 'Alfa'
choose_file_to_upload = 'Scegli il file da caricare'
left = 'Sinistro'
top = 'Cima'
right = 'Destra'
bottom = 'Piedi'
feathering = 'Piumaggio'
low_threshold = 'Soglia bassa'
high_threshold = 'Soglia alta'
filename_prefix = 'Nome file prefisso'
color = 'Colore'
channel = 'Canale'
connect_to_widget_input = "Connettiti all'input del widget"
red = 'Rosso'
green = 'Verde'
blue = 'Blu'
value = 'Valore'
operation = 'Funzionamento'
expand = 'Espandere'
tapered_corners = 'Angoli affusolati'
ratio = 'Rapporto'
samples1 = 'Campioni1'
samples2 = 'Campioni2'
model_path = 'Percorso del modello'
config_name = 'Nome di configurazione'
unet_name = 'Unet nome'
clip_name1 = 'Nome clip1'
clip_name2 = 'Nome clip2'
start = 'Inizio'
end = 'Fine'
crop_w = 'Crop w'
crop_h = 'Raccolto h'
target_width = 'Larghezza target'
target_height = 'Altezza target'
text_g = 'Testo g'
text_l = 'Testo l'
ascore = 'Ascore'
model1 = 'Modello1'
model2 = 'Modello2'