# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[flows]
inputs = "ingressi"
outputs = "uscite"
widgets = "widget"

[values]
fixed = "fisso"
randomize = "randomizzare"
increment = "incremento"
decrement = "decremento"
nearest-exact = "più vicino-esatto"
bilinear = "bilineare"
area = "area"
bislerp = "bislerp"
bicubic = "bicubico"
enabled = "abilitato"
disabled = "disabilitato"
normal = "normale"
multiply = "moltiplicare"
screen = "schermo"
overlay = "sovrapposizione"
soft_light = "luce soffusa"
none = "nessuno"
floyd-steinberg = "floyd-steinberg"
bayer-2 = "bayer-2"
bayer-4 = "bayer-4"
bayer-8 = "bayer-8"
bayer-16 = "Bayer-16"
add = "aggiungi"
subtract = "sottrai"
and = "e"
or = "oppure"
xor = "xor"

[types]
model = "modello"
clip = "clip"
vae = "vae"
conditioning = "condizionamento"
positive = "positivo"
negative = "negativo"
latent = "latente"
latent_image = "immagine latente"
samples = "campioni"
image = "immagine"
seed = "seme"
steps = "passi"
cfg = "cfg"
sampler_name = "nome del campionatore"
scheduler = "pianificatore"
denoise = "denoise"
add_noise = "aggiungi rumore"
noise_seed = "seme di rumore"
control_after_generate = "controllo dopo la generazione"
return_with_leftover_noise = "ritorna con il rumore residuo"
start_at_step = "inizia dal passaggio"
end_at_step = "fine al passaggio"
ckpt_name = "nome ckpt"
vae_name = "nome vae"
pixels = "pixel"
mask = "maschera"
lora_name = "nome lora"
strength_model = "modello di forza"
strength_clip = "clip di forza"
clip_name = "nome clip"
control_net = "rete di controllo"
control_net_name = "nome della rete di controllo"
clip_vision = "clip visione"
style_model = "modello di stile"
style_model_name = "nome modello stile"
gligen_name = "nome gligen"
gligen = "gligen"
model_name = "nome modello"
upscale_model = "modello di lusso"
hypernetwork_name = "nome iperrete"
strength = "forza"
clip_vision_output = "Uscita visione clip"
conditioning_to = "condizionamento a"
conditioning_from = "condizionamento da"
conditioning_to_strength = "condizionamento alla forza"
conditioning_1 = "condizionamento 1"
conditioning_2 = "condizionamento 2"
gligen_textbox_model = "modello di casella di testo gligen"
text = "testo"
width = "larghezza"
height = "altezza"
length = "lunghezza"
x = "x"
y = "y"
stop_at_clip_layer = "fermati al livello clip"
set_cond_area = "imposta area di cond"
default = "predefinito"
mask_bounds = "limiti maschera"
noise_augmentation = "aumento del rumore"
start_percent = "percentuale iniziale"
end_percent = "fine percentuale"
grow_mask_by = "maschera di coltivazione di"
batch_index = "indice batch"
amount  = "importo = '"
batch_size = "dimensione del lotto"
rotation = "rotazione"
none = "nessuno"
ninety_degrees = "novanta gradi"
oneeighty_degrees = "unottanta gradi"
twoseventy_degrees = "duesetta gradi"
flip_method = "metodo di inversione"
x-axis_vertically = "asse x verticalmente"
y-axis_horizontally = "asse y orizzontalmente"
upscale_method = "metodo di upscaling"
crop = "ritaglio"
scale_by = "scala per"
samples_to = "campioni a"
samples_from = "Campioni da"
feather = "piuma"
destination = "destinazione"
source = "fonte"
resize_source = "ridimensiona sorgente"
megapixels = "megapixel"
image1 = "immagine 1"
image2 = "immagine 2"
blend_factor = "fattore di fusione"
blend_mode = "modalità di fusione"
blur_radius = "raggio di sfocatura"
sigma = "sigma"
colors = "colori"
dither = "rassicurante"
sharpen_radius = "Aumenta raggio"
alpha = "alfa"
choose_file_to_upload = "scegli il file da caricare"
left = "a sinistra"
top = "inizio"
right = "a destra"
bottom = "in basso"
feathering = "piumaggio"
low_threshold = "soglia bassa"
high_threshold = "soglia alta"
filename_prefix = "prefisso nome file"
color = "colore"
channel = "canale"
connect_to_widget_input = "connetti all'ingresso del widget"
red = "rosso"
green = "verde"
blue = "blu"
value = "valore"
operation = "funzionamento"
expand = "espandere"
tapered_corners = "angoli affusolati"
ratio = "rapporto"
samples1 = "campioni1"
samples2 = "campioni2"
model_path = "percorso del modello"
config_name = "nome configurazione"
unet_name = "unet nome"
clip_name1 = "nome clip1"
clip_name2 = "nome clip 2"
start = "inizio"
end = "fine"
crop_w = "ritaglio w"
crop_h = "raccolto h"
target_width = "larghezza target"
target_height = "altezza target"
text_g = "testo g"
text_l = "testo l"
ascore = "ascore"
model1 = "modello1"
model2 = "modello 2"