# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[titles]
Note = 'Σημείωση'
PrimitiveNode = 'Πρωτόγονος κόμβος'
Reroute = 'Αναδρομολόγηση'
Sampler = 'Δειγματολήπτης'
SamplerAdvanced = 'Δειγματολήπτης για προχωρημένους'
CheckpointLoaderSimple = 'Checkpoint Loader Απλή'
VAELoader = 'Φορτωτής VAE'
LoraLoader = 'Φορτωτής Lora'
ControlNetLoader = 'Φορτωτής ControlNet'
DiffControlNetLoader = 'Φορτωτής DiffControlNet'
StyleModelLoader = 'Στυλ Μοντέλο Loader'
CLIPVisionLoader = 'Φορτωτής όρασης CLIP'
unCLIPCheckpointLoader = 'unCLIP φορτωτής σημείων ελέγχου'
GLIGENLoader = 'Φορτωτής GLIGEN'
UpscaleModelLoader = 'Αναβαθμισμένος φορτωτής μοντέλου'
HypernetworkLoader = 'Hypernetwork Loader'
StyleModelApply = 'Εφαρμογή μοντέλου στυλ'
GLIGENTextBoxApply = 'Εφαρμογή πλαισίου κειμένου GLIGEN'
CLIPTextEncode = 'Κωδικοποίηση κειμένου CLIP'
CLIPSetLastLayer = 'CLIP Set Τελευταίο Στρώμα'
ConditioningAverage = 'Μέσος όρος κλιματισμού'
ConditioningCombine = 'Συνδυασμός κλιματισμού'
ConditioningConcat = 'Κλιματισμός Concat'
ConditioningSetArea = 'Περιοχή σετ κλιματισμού'
ConditioningSetAreaPercentage = 'Ποσοστό περιοχής ρύθμισης κλιματισμού'
ConditioningSetMask = 'Σετ Κλιματισμού Μάσκα'
CLIPVisionEncode = 'Κωδικοποίηση όρασης CLIP'
unCLIPConditioning = 'unCLIP Κλιματισμός'
ControlNetApply = 'Εφαρμογή ControlNet'
ControlNetApplyAdvanced = 'ControlNet Εφαρμογή Advanced'
VAEEncodeForInpaint = 'Κωδικοποίηση VAE για Inpaint'
SetLatentNoiseMask = 'Ορισμός μάσκας λανθάνοντος θορύβου'
LatentFromBatch = 'Λανθάνουσα από παρτίδα'
RepeatLatentBatch = 'Επανάληψη λανθάνουσας παρτίδας'
RebatchLatents = 'Λανθάνουσες παρτίδας'
LatentRotate = 'Λανθάνουσα περιστροφή'
LatentFlip = 'Λανθάνουσα αναστροφή'
LatentCrop = 'Λανθάνουσα καλλιέργεια'
VAEDecode = 'Αποκωδικοποίηση VAE'
VAEEncode = 'Κωδικοποίηση VAE'
EmptyLatentImage = 'Κενή λανθάνουσα εικόνα'
LatentUpscale = 'Λανθάνουσα αναβάθμιση'
LatentUpscaleBy = 'Λανθάνουσα αναβάθμιση από'
LatentComposite = 'Λανθάνον σύνθετο'
LatentCompositeMasked = 'Λανθάνουσα σύνθετη μάσκα'
ImageScale = 'Κλίμακα εικόνας'
ImageScaleBy = 'Κλίμακα εικόνας κατά'
ImageUpscaleWithModel = 'Αναβάθμιση εικόνας με μοντέλο'
ImageScaleToTotalPixels = 'Κλίμακα εικόνας σε συνολικά εικονοστοιχεία'
ImageBlend = 'Μείγμα εικόνας'
ImageBlur = 'Θάμπωμα εικόνας'
ImageQuantize = 'Κβαντοποίηση εικόνας'
ImageSharpen = 'Όξυνση εικόνας'
Canny = 'Κάνυ'
SaveImage = 'Αποθήκευση εικόνας'
PreviewImage = 'Προεπισκόπηση εικόνας'
LoadImage = 'Φόρτωση εικόνας'
ImageInvert = 'Αντιστροφή εικόνας'
ImageBatch = 'Παρτίδα εικόνας'
ImagePadForOutpaint = 'Image Pad Για Outpaint'
EmptyImage = 'Κενή εικόνα'
ImageCompositeMasked = 'Σύνθετη εικόνα καλυμμένη'
LoadImageMask = 'Φόρτωση μάσκας εικόνας'
MaskToImage = 'Μάσκα σε εικόνα'
ImageToMask = 'Εικόνα για μάσκα'
ImageColorToMask = 'Χρώμα εικόνας για μάσκα'
SolidMask = 'Στερεά μάσκα'
InvertMask = 'Αντιστροφή μάσκας'
CropMask = 'Μάσκα περικοπής'
MaskComposite = 'Σύνθετη μάσκα'
FeatherMask= 'Μάσκα φτερών'
GrowMask = 'Grow Μάσκα'
VAEDecodeTiled = 'VAE Αποκωδικοποίηση πλακιδίων'
VAEEncodeTiled = 'Κωδικοποίηση VAE με πλακάκια'
TomePatchModel = 'Tome Patch Μοντέλο'
SaveLatent = 'Αποθήκευση λανθάνουσας'
LoadLatent = 'Λανθάνουσα φόρτωση'
LatentBlend = 'Λανθάνον μείγμα'
DiffusersLoader = 'Φορτωτής διαχυτών'
CLIPLoader = 'Φορτωτής CLIP'
CheckpointLoader = 'Φορτωτής σημείων ελέγχου'
UNETLoader = 'Φορτωτής UNET'
DualCLIPLoader = 'Διπλός φορτωτής CLIP'
ConditioningZeroOut = 'Κλιματισμός μηδέν έξω'
ConditioningSetTimestepRange = 'Ρύθμιση χρονοδιαγράμματος κλιματισμού'
CLIPTextEncodeSDXL = 'Κωδικοποίηση κειμένου CLIP SDXL'
CLIPTextEncodeSDXLRefiner = 'Κωδικοποίηση κειμένου CLIP SDXL Refiner'
ModelMergeSimple = 'Απλή συγχώνευση μοντέλου'
ModelMergeBlocs = 'Μπλοκ συγχώνευσης μοντέλων'
CheckpointSave = 'Αποθήκευση σημείου ελέγχου'
CLIPMergeSimple = 'CLIP Συγχώνευση Απλή'
ModelMergeBlockNumber = 'Αριθμός μπλοκ συγχώνευσης μοντέλου'
ModelMergeSDXL = 'Συγχώνευση μοντέλου SDXL'
ModelMergeSDXLTransformers = 'Μετασχηματιστές SDXL συγχώνευσης μοντέλου'
ModelMergeSDXLDetailedTransformers = 'Μοντέλο συγχώνευσης SDXL λεπτομερείς μετασχηματιστές'
