# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[titles]
Note = 'Note'
PrimitiveNode = 'Nœud primitif'
Reroute = "Changer l'itinéraire de"
Sampler = 'Abécédaire'
SamplerAdvanced = 'Échantillonneur Avancé'
CheckpointLoaderSimple = 'Chargeur de point de contrôle simple'
VAELoader = 'Chargeur VAE'
LoraLoader = 'Chargeur Lora'
ControlNetLoader = 'Chargeur ControlNet'
DiffControlNetLoader = 'Chargeur DiffControlNet'
StyleModelLoader = 'Modèle de style Chargeur'
CLIPVisionLoader = 'Chargeur de vision CLIP'
unCLIPCheckpointLoader = 'Chargeur de points de contrôle unCLIP'
GLIGENLoader = 'Chargeur GLIGEN'
UpscaleModelLoader = 'Chargeur de modèles haut de gamme'
HypernetworkLoader = 'Chargeur hyperréseau'
StyleModelApply = 'Modèle de style Appliquer'
GLIGENTextBoxApply = 'Boîte de texte GLIGEN Appliquer'
CLIPTextEncode = 'Encodage de texte CLIP'
CLIPSetLastLayer = 'CLIP Définir le dernier calque'
ConditioningAverage = 'Conditionnement Moyen'
ConditioningCombine = 'Moissonneuse-batteuse de conditionnement'
ConditioningConcat = 'Conditionnement Concat'
ConditioningSetArea = 'Zone de conditionnement'
ConditioningSetAreaPercentage = "Pourcentage de surface de l'ensemble de conditionnement"
ConditioningSetMask = 'Masque de conditionnement'
CLIPVisionEncode = 'Encodage de vision CLIP'
unCLIPConditioning = 'Conditionnement unCLIP'
ControlNetApply = 'ControlNet Appliquer'
ControlNetApplyAdvanced = 'ControlNet Appliquer Advanced'
VAEEncodeForInpaint = 'Encode VAE Pour Inpaint'
SetLatentNoiseMask = 'Définir un masque de bruit latent'
LatentFromBatch = 'Latent à partir du lot'
RepeatLatentBatch = 'Répéter le lot latent'
RebatchLatents = 'Rebatch Latents'
LatentRotate = 'Rotation latente'
LatentFlip = 'Flip latent'
LatentCrop = 'Culture latente'
VAEDecode = 'Décodage VAE'
VAEEncode = 'Encodage VAE'
EmptyLatentImage = 'Image latente vide'
LatentUpscale = 'Haut De Gamme Latent'
LatentUpscaleBy = 'Haut De Gamme Latent Par'
LatentComposite = 'Composite latent'
LatentCompositeMasked = 'Composite latent masqué'
ImageScale = "Échelle de l'image"
ImageScaleBy = "Échelle De L'image Par"
ImageUpscaleWithModel = 'Image Haut De Gamme Avec Modèle'
ImageScaleToTotalPixels = "Échelle De L'image Au Nombre Total De Pixels"
ImageBlend = "Mélange d'images"
ImageBlur = "Flou d'image"
ImageQuantize = "Quantification de l'image"
ImageSharpen = "Aiguiser l'image"
Canny = 'Futé, malin (ou maligne)'
SaveImage = "Enregistrer l'image"
PreviewImage = "Prévisualiser l'image"
LoadImage = "Charger l'image"
ImageInvert = "Inverser l'image"
ImageBatch = "Lot d'images"
ImagePadForOutpaint = "Tampon D'image Pour Outpaint"
EmptyImage = 'Image vide'
ImageCompositeMasked = 'Image composite masquée'
LoadImageMask = "Masque de chargement de l'image"
MaskToImage = "Masque à l'image"
ImageToMask = 'Image à masquer'
ImageColorToMask = "Couleur de l'image à masquer"
SolidMask = 'Masque solide'
InvertMask = 'Masque inversé'
CropMask = 'Masque de récolte'
MaskComposite = 'Masque Composite'
FeatherMask= 'Masque en plumes'
GrowMask = 'Masque de culture'
VAEDecodeTiled = 'VAE Décodage Carrelé'
VAEEncodeTiled = 'VAE Encode Tiled'
TomePatchModel = 'Modèle de patch Tome'
SaveLatent = 'Sauvegarder latent'
LoadLatent = 'Charge latente'
LatentBlend = 'Mélange latent'
DiffusersLoader = 'Chargeur de diffuseurs'
CLIPLoader = 'Chargeur CLIP'
CheckpointLoader = 'Chargeur de point de contrôle'
UNETLoader = 'Chargeur UNET'
DualCLIPLoader = 'Chargeur double CLIP'
ConditioningZeroOut = 'Conditionnement Zero Out'
ConditioningSetTimestepRange = 'Plage de temps du jeu de conditionnement'
CLIPTextEncodeSDXL = 'CLIP Encodage texte SDXL'
CLIPTextEncodeSDXLRefiner = 'CLIP Encode de texte SDXL Refiner'
ModelMergeSimple = 'Modèle Fusion Simple'
ModelMergeBlocs = 'Blocs de fusion de modèles'
CheckpointSave = 'Enregistrer au point de contrôle'
CLIPMergeSimple = 'CLIP Fusionner Simple'
ModelMergeBlockNumber = 'Numéro de bloc de fusion du modèle'
ModelMergeSDXL = 'Modèle Fusionner SDXL'
ModelMergeSDXLTransformers = 'Transformateurs Model Merge SDXL'
ModelMergeSDXLDetailedTransformers = 'Transformateurs détaillés Model Merge SDXL'