# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[flows]
inputs = "Entrées d'entrées"
outputs = "Sorties d'entrée"
widgets = 'Widgets'
	
[values]	
fixed = 'Fixe'
randomize = 'Randomiser'
increment = 'Augmentation (automatique)'
decrement = 'Décrément'
nearest-exact = 'Le plus proche-exact'
bilinear = 'Bilinéaire'
area = 'Région'
bislerp = 'Bislerp'
bicubic = 'Bicubique'
enabled = 'Activé'
disabled = 'Handicapé'
normal = 'Normale'
multiply = 'Multiplier'
screen = 'Écran'
overlay = 'Transparent'
soft_light = 'Lumière douce'
none = 'Aucun (ou aucune)'
floyd-steinberg = 'Floyd-steinberg'
bayer-2 = 'Bayer-2'
bayer-4 = 'Bayer-4'
bayer-8 = 'Bayer-8'
bayer-16 = 'Bayer-16'
add = 'Ajouter, rajouter'
subtract = 'Soustraire'
and = 'Et'
or = 'Ou'
xor = 'Xor'
	
[types]	
model = 'Maquette'
clip = 'Pince'
vae = 'Vae'
conditioning = 'Conditionnement'
positive = 'Affirmatif'
negative = 'Réponse négative'
latent = 'Latent'
latent_image = 'Image latente'
samples = 'Échantillons'
image = 'Image'
seed = 'Graine'
steps = 'Étapes'
cfg = 'Cfg'
sampler_name = "Nom de l'échantillonneur"
scheduler = 'Planificateureur'
denoise = 'Débruit'
add_noise = 'Ajouter du bruit'
noise_seed = 'Graine de bruit'
control_after_generate = 'Contrôle après génération'
return_with_leftover_noise = 'Retour avec les restes de bruit'
start_at_step = 'Commencer par étape'
end_at_step = "Fin à l'étape"
ckpt_name = 'Nom de ckpt'
vae_name = 'Nom de la vae'
pixels = 'Pixels'
mask = 'Masque'
lora_name = 'Nom de lora'
strength_model = 'Modèle de force'
strength_clip = 'Clip de force'
clip_name = 'Nom du clip'
control_net = 'Filet de contrôle'
control_net_name = 'Contrôler le nom du réseau'
clip_vision = 'Vision clip'
style_model = 'Modèle de style'
style_model_name = 'Nom du modèle de style'
gligen_name = 'Nom de gligen'
gligen = 'Gligen'
model_name = 'Nom du modèle'
upscale_model = 'Modèle haut de gamme'
hypernetwork_name = "Nom de l'hyperréseau"
strength = 'Force'
clip_vision_output = 'Sortie de vision clip'
conditioning_to = 'Conditionnement à'
conditioning_from = 'Conditionnement à partir de'
conditioning_to_strength = 'Conditionnement à la force'
conditioning_1 = 'Conditionnement 1'
conditioning_2 = 'Conditionnement 2'
gligen_textbox_model = 'Modèle de zone de texte gligen'
text = 'Texte'
width = 'Largeur'
height = 'Taille'
length = 'Longueur'
x = 'X, x'
y = 'Y, y'
stop_at_clip_layer = 'Arrêt au calque clip'
set_cond_area = 'Définir la zone du cône'
default = 'Non-remboursement'
mask_bounds = 'Limites du masque'
noise_augmentation = 'Augmentation du bruit'
start_percent = 'Pourcentage de départ'
end_percent = 'Pourcentage final'
grow_mask_by = 'Faire pousser le masque par'
batch_index = 'Index des lots'
amount = 'Montant'
batch_size = 'Taille du lot'
rotation = 'Rotation'
none = 'Aucun (ou aucune)'
ninety_degrees = 'Quatre-vingt-dix degrés'
oneeighty_degrees = 'Unighty degrés'
twoseventy_degrees = 'Soixante-dix degrés'
flip_method = 'Méthode de retournement'
x-axis_vertically = 'Axe des x verticalement'
y-axis_horizontally = 'Axe des y horizontalement'
upscale_method = 'Méthode haut de gamme'
crop = 'Culture'
scale_by = 'Échelle par'
samples_to = 'Échantillons à'
samples_from = 'Échantillons de'
feather = 'Plume'
destination = 'Destination'
source = 'Source'
resize_source = 'Redimensionner la source'
megapixels = 'Mégapixels'
image1 = 'Image1'
image2 = 'Image2'
blend_factor = 'Facteur de mélange'
blend_mode = 'Mode de fusion'
blur_radius = 'Rayon de flou'
sigma = 'Sigma'
colors = 'Couleurs'
dither = 'Tergiverser'
sharpen_radius = 'Aiguiser le rayon'
alpha = 'Alpha'
choose_file_to_upload = 'Choisir le fichier à télécharger'
left = 'Gauche'
top = 'Haut'
right = 'Droite'
bottom = 'Pied'
feathering = 'Mise en drapeau'
low_threshold = 'Seuil bas'
high_threshold = 'Seuil élevé'
filename_prefix = 'Préfixe du nom de fichier'
color = 'Couleur'
channel = 'Canal'
connect_to_widget_input = "Se connecter à l'entrée du widget"
red = 'Rouge'
green = 'Vert'
blue = 'Bleu'
value = 'Valeur'
operation = 'Fonctionnement'
expand = 'Développer'
tapered_corners = 'Coins effilés'
ratio = 'Rapport'
samples1 = 'Échantillons1'
samples2 = 'Échantillons2'
model_path = 'Chemin du modèle'
config_name = 'Nom de la configuration'
unet_name = "Nom d'unet"
clip_name1 = 'Nom du clip1'
clip_name2 = 'Nom du clip2'
start = 'Début'
end = 'Fin'
crop_w = 'Culture w'
crop_h = 'Culture h'
target_width = 'Largeur cible'
target_height = 'Hauteur cible'
text_g = 'Texte g'
text_l = 'Texte l'
ascore = 'Ascore'
model1 = 'Modèle1'
model2 = 'Modèle2'