# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[titles]
Note = 'Billete'
PrimitiveNode = 'Nodo primitivo'
Reroute = 'Desviar'
Sampler = 'Muestrario'
SamplerAdvanced = 'Sampler Advanced'
CheckpointLoaderSimple = 'Cargador de puntos de control sencillo'
VAELoader = 'Cargador VAE'
LoraLoader = 'Cargador Lora'
ControlNetLoader = 'Cargador de ControlNet'
DiffControlNetLoader = 'Cargador DiffControlNet'
StyleModelLoader = 'Cargador de modelos de estilo'
CLIPVisionLoader = 'Cargador de visión CLIP'
unCLIPCheckpointLoader = 'Cargador de puntos de control unCLIP'
GLIGENLoader = 'Cargador GLIGEN'
UpscaleModelLoader = 'Cargador de modelos de lujo'
HypernetworkLoader = 'Cargador de hiperred'
StyleModelApply = 'Modelo de estilo Aplicar'
GLIGENTextBoxApply = 'Cuadro de texto GLIGEN Aplicar'
CLIPTextEncode = 'Codificación de texto CLIP'
CLIPSetLastLayer = 'CLIP Establecer la última capa'
ConditioningAverage = 'Promedio de acondicionamiento'
ConditioningCombine = 'Condicionamiento Combinar'
ConditioningConcat = 'Acondicionador Concat'
ConditioningSetArea = 'Zona del juego de acondicionamiento'
ConditioningSetAreaPercentage = 'Porcentaje de área del conjunto de acondicionamiento'
ConditioningSetMask = 'Máscara del juego de acondicionamiento'
CLIPVisionEncode = 'Codificación de visión CLIP'
unCLIPConditioning = 'Acondicionamiento unCLIP'
ControlNetApply = 'Aplicación de ControlNet'
ControlNetApplyAdvanced = 'ControlNet Aplicar Avanzado'
VAEEncodeForInpaint = 'Codificación VAE Para Inpaint'
SetLatentNoiseMask = 'Establecer máscara de ruido latente'
LatentFromBatch = 'Latente desde el lote'
RepeatLatentBatch = 'Repetir lote latente'
RebatchLatents = 'Latentes de rebatch'
LatentRotate = 'Rotación latente'
LatentFlip = 'Volteo latente'
LatentCrop = 'Cultivo latente'
VAEDecode = 'Decodificación VAE'
VAEEncode = 'Codificación VAE'
EmptyLatentImage = 'Imagen latente vacía'
LatentUpscale = 'Latente de lujo'
LatentUpscaleBy = 'Latente de lujo por'
LatentComposite = 'Compuesto latente'
LatentCompositeMasked = 'Compuesto latente enmascarado'
ImageScale = 'Escala de imagen'
ImageScaleBy = 'Escala de imagen por'
ImageUpscaleWithModel = 'Imagen De Lujo Con Modelo'
ImageScaleToTotalPixels = 'Escala De Imagen A Píxeles Totales'
ImageBlend = 'Mezcla de imágenes'
ImageBlur = 'Desenfoque de la imagen'
ImageQuantize = 'Cuantizar la imagen'
ImageSharpen = 'Imagen Enfocar'
Canny = 'Astuto'
SaveImage = 'Guardar imagen'
PreviewImage = 'Vista previa de la imagen'
LoadImage = 'Cargar imagen'
ImageInvert = 'Invertir imagen'
ImageBatch = 'Lote de imágenes'
ImagePadForOutpaint = 'Almohadilla De Imagen Para Outpaint'
EmptyImage = 'Imagen vacía'
ImageCompositeMasked = 'Imagen compuesta enmascarada'
LoadImageMask = 'Cargar máscara de imagen'
MaskToImage = 'Máscara A La Imagen'
ImageToMask = 'Imagen Para Enmascarar'
ImageColorToMask = 'Color De La Imagen Para Enmascarar'
SolidMask = 'Máscara sólida'
InvertMask = 'Invertir máscara'
CropMask = 'Máscara de cultivo'
MaskComposite = 'Mascarilla compuesta'
FeatherMask= 'Máscara de plumas'
GrowMask = 'Máscara de cultivo'
VAEDecodeTiled = 'Decodificación de VAE en mosaico'
VAEEncodeTiled = 'VAE Encode Tiled'
TomePatchModel = 'Modelo de parche Tome'
SaveLatent = 'Guardar Latent'
LoadLatent = 'Carga latente'
LatentBlend = 'Mezcla latente'
DiffusersLoader = 'Cargador de difusores'
CLIPLoader = 'Cargador CLIP'
CheckpointLoader = 'Cargador de puntos de control'
UNETLoader = 'Cargador UNET'
DualCLIPLoader = 'Cargador CLIP dual'
ConditioningZeroOut = 'Acondicionamiento cero salida'
ConditioningSetTimestepRange = 'Rango de paso de tiempo del conjunto de acondicionamiento'
CLIPTextEncodeSDXL = 'Codificación de texto CLIP SDXL'
CLIPTextEncodeSDXLRefiner = 'Refinador SDXL de codificación de texto CLIP'
ModelMergeSimple = 'Modelo Merge Simple'
ModelMergeBlocs = 'Bloques de fusión de modelos'
CheckpointSave = 'Guardar punto de control'
CLIPMergeSimple = 'CLIP Merge Simple'
ModelMergeBlockNumber = 'Número de bloque de fusión del modelo'
ModelMergeSDXL = 'Modelo Merge SDXL'
ModelMergeSDXLTransformers = 'Modelo Combinar transformadores SDXL'
ModelMergeSDXLDetailedTransformers = 'Transformadores detallados del modelo Merge SDXL'