# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[flows]
inputs = 'Entradas de entrada'
outputs = 'Salidas'
widgets = 'Widgets'
	
[values]	
fixed = 'Fijo'
randomize = 'Aleatorizar'
increment = 'Incremento'
decrement = 'Disminución'
nearest-exact = 'Más cercano-exacto'
bilinear = 'Bilineal'
area = 'Zona'
bislerp = 'Bislerp'
bicubic = 'Bicúbico'
enabled = 'Activado'
disabled = 'Discapacitado'
normal = 'Normal'
multiply = 'Multiplicar'
screen = 'Cortina'
overlay = 'Capa'
soft_light = 'Luz suave'
none = 'Ninguno'
floyd-steinberg = 'Floyd-steinberg'
bayer-2 = 'Bayer-2'
bayer-4 = 'Bayer-4'
bayer-8 = 'Bayer-8'
bayer-16 = 'Bayer-16'
add = 'Añadir'
subtract = 'Restar'
and = 'Y'
or = 'Quirófano'
xor = 'Xor'
	
[types]	
model = 'Maniquí'
clip = 'Clip'
vae = 'Vae'
conditioning = 'Condicionamiento'
positive = 'Positivo'
negative = 'Negativa'
latent = 'Latente'
latent_image = 'Imagen latente'
samples = 'Muestras'
image = 'Efigie'
seed = 'Semilla'
steps = 'Escalones'
cfg = 'Cfg'
sampler_name = 'Nombre del sampler'
scheduler = 'Programador'
denoise = 'Denoise'
add_noise = 'Añadir ruido'
noise_seed = 'Semilla de ruido'
control_after_generate = 'Control después de generar'
return_with_leftover_noise = 'Retorno con ruido sobrante'
start_at_step = 'Empezar en el paso'
end_at_step = 'Terminar en el paso'
ckpt_name = 'Nombre de ckpt'
vae_name = 'Nombre vae'
pixels = 'Pixeles'
mask = 'Máscara'
lora_name = 'Nombre de lora'
strength_model = 'Modelo de fuerza'
strength_clip = 'Clip de fuerza'
clip_name = 'Nombre del clip'
control_net = 'Red de control'
control_net_name = 'Nombre de red de control'
clip_vision = 'Visión del clip'
style_model = 'Modelo de estilo'
style_model_name = 'Nombre del modelo de estilo'
gligen_name = 'Nombre del gligen'
gligen = 'Gligen'
model_name = 'Nombre del modelo'
upscale_model = 'Modelo de lujo'
hypernetwork_name = 'Nombre de la hiperred'
strength = 'Fuerza'
clip_vision_output = 'Salida de visión de clip'
conditioning_to = 'Acondicionamiento para'
conditioning_from = 'Acondicionamiento de'
conditioning_to_strength = 'Acondicionamiento a la fuerza'
conditioning_1 = 'Acondicionamiento 1'
conditioning_2 = 'Acondicionamiento 2'
gligen_textbox_model = 'Modelo de cuadro de texto gligen'
text = 'Libro de texto'
width = 'Ancho'
height = 'Cima'
length = 'Longitud'
x = 'X'
y = 'Y'
stop_at_clip_layer = 'Detenerse en la capa de clip'
set_cond_area = 'Establecer el área de cond'
default = 'Valor por defecto'
mask_bounds = 'Límites de máscara'
noise_augmentation = 'Aumento de ruido'
start_percent = 'Porcentaje de inicio'
end_percent = 'Porcentaje final'
grow_mask_by = 'Hacer crecer la máscara por'
batch_index = 'Índice de lotes'
amount = 'Cantidad'
batch_size = 'Tamaño del lote'
rotation = 'Giro'
none = 'Ninguno'
ninety_degrees = 'Noventa grados'
oneeighty_degrees = 'Unoocho grados'
twoseventy_degrees = 'Dos setenta grados'
flip_method = 'Método flip'
x-axis_vertically = 'Eje x verticalmente'
y-axis_horizontally = 'Eje y horizontalmente'
upscale_method = 'Método de lujo'
crop = 'Cosecha'
scale_by = 'Escalar por'
samples_to = 'Muestras para'
samples_from = 'Muestras de'
feather = 'Pluma'
destination = 'Destino'
source = 'Origen'
resize_source = 'Cambiar el tamaño de la fuente'
megapixels = 'Megapíxeles'
image1 = 'Imagen1'
image2 = 'Imagen2'
blend_factor = 'Factor de mezcla'
blend_mode = 'Modo de fusión'
blur_radius = 'Radio de desenfoque'
sigma = 'Sigma'
colors = 'Color'
dither = 'Ponerse muy nervioso'
sharpen_radius = 'Afilar el radio'
alpha = 'Alfa'
choose_file_to_upload = 'Elegir el archivo que desea cargar'
left = 'Izquierda'
top = 'Cima'
right = 'Derecho'
bottom = 'Inferior'
feathering = 'Plumas'
low_threshold = 'Umbral bajo'
high_threshold = 'Umbral alto'
filename_prefix = 'Prefijo de nombre de archivo'
color = 'Color'
channel = 'Canal'
connect_to_widget_input = 'Conectarse a la entrada del widget'
red = 'Rojo'
green = 'Verde'
blue = 'Azul'
value = 'Valor'
operation = 'Funcionamiento'
expand = 'Expandir'
tapered_corners = 'Esquinas cónicas'
ratio = 'Ratio'
samples1 = 'Muestras1'
samples2 = 'Muestras2'
model_path = 'Ruta del modelo'
config_name = 'Nombre de configuración'
unet_name = 'Unet name'
clip_name1 = 'Nombre del clip1'
clip_name2 = 'Nombre del clip2'
start = 'Comienzo'
end = 'Conclusión'
crop_w = 'Cultivo w'
crop_h = 'Cultivo h'
target_width = 'Ancho objetivo'
target_height = 'Altura del objetivo'
text_g = 'Texto g'
text_l = 'Texto l'
ascore = 'Ascore'
model1 = 'Modelo1'
model2 = 'Modelo2'