# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[titles]
Note = ''
PrimitiveNode = ''
Reroute = ''
Sampler = ''
SamplerAdvanced = ''
CheckpointLoaderSimple = ''
VAELoader = ''
LoraLoader = ''
ControlNetLoader = ''
DiffControlNetLoader = ''
StyleModelLoader = ''
CLIPVisionLoader = ''
unCLIPCheckpointLoader = ''
GLIGENLoader = ''
UpscaleModelLoader = ''
HypernetworkLoader = ''
StyleModelApply = ''
GLIGENTextBoxApply = ''
CLIPTextEncode = ''
CLIPSetLastLayer = ''
ConditioningAverage = ''
ConditioningCombine = ''
ConditioningConcat = ''
ConditioningSetArea = ''
ConditioningSetAreaPercentage = ''
ConditioningSetMask = ''
CLIPVisionEncode = ''
unCLIPConditioning = ''
ControlNetApply = ''
ControlNetApplyAdvanced = ''
VAEEncodeForInpaint = ''
SetLatentNoiseMask = ''
LatentFromBatch = ''
RepeatLatentBatch = ''
RebatchLatents = ''
LatentRotate = ''
LatentFlip = ''
LatentCrop = ''
VAEDecode = ''
VAEEncode = ''
EmptyLatentImage = ''
LatentUpscale = ''
LatentUpscaleBy = ''
LatentComposite = ''
LatentCompositeMasked = ''
ImageScale = ''
ImageScaleBy = ''
ImageUpscaleWithModel = ''
ImageScaleToTotalPixels = ''
ImageBlend = ''
ImageBlur = ''
ImageQuantize = ''
ImageSharpen = ''
Canny = ''
SaveImage = ''
PreviewImage = ''
LoadImage = ''
ImageInvert = ''
ImageBatch = ''
ImagePadForOutpaint = ''
EmptyImage = ''
ImageCompositeMasked = ''
LoadImageMask = ''
MaskToImage = ''
ImageToMask = ''
ImageColorToMask = ''
SolidMask = ''
InvertMask = ''
CropMask = ''
MaskComposite = ''
FeatherMask= ''
GrowMask = ''
VAEDecodeTiled = ''
VAEEncodeTiled = ''
TomePatchModel = ''
SaveLatent = ''
LoadLatent = ''
LatentBlend = ''
DiffusersLoader = ''
CLIPLoader = ''
CheckpointLoader = ''
UNETLoader = ''
DualCLIPLoader = ''
ConditioningZeroOut = ''
ConditioningSetTimestepRange = ''
CLIPTextEncodeSDXL = ''
CLIPTextEncodeSDXLRefiner = ''
ModelMergeSimple = ''
ModelMergeBlocs = ''
CheckpointSave = ''
CLIPMergeSimple = ''
ModelMergeBlockNumber = ''
ModelMergeSDXL = ''
ModelMergeSDXLTransformers = ''
ModelMergeSDXLDetailedTransformers = ''
