# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[flows]
inputs = ''
outputs = ''
widgets = ''

[values]
fixed = ''
randomize = ''
increment = ''
decrement = ''
nearest-exact = ''
bilinear = ''
area = ''
bislerp = ''
bicubic = ''
enabled = ''
disabled = ''
normal = ''
multiply = ''
screen = ''
overlay = ''
soft_light = ''
none = ''
floyd-steinberg = ''
bayer-2 = ''
bayer-4 = ''
bayer-8 = ''
bayer-16 = ''
add = ''
subtract = ''
and = ''
or = ''
xor = ''

[types]
model = ''
clip = ''
vae = ''
conditioning = ''
positive = ''
negative = ''
latent = ''
latent_image = ''
samples = ''
image = ''
seed = ''
steps = ''
cfg = ''
sampler_name = ''
scheduler = ''
denoise = ''
add_noise = ''
noise_seed = ''
control_after_generate = ''
return_with_leftover_noise = ''
start_at_step = ''
end_at_step = ''
ckpt_name = ''
vae_name = ''
pixels = ''
mask = ''
lora_name = ''
strength_model = ''
strength_clip = ''
clip_name = ''
control_net = ''
control_net_name = ''
clip_vision = ''
style_model = ''
style_model_name = ''
gligen_name = ''
gligen = ''
model_name = ''
upscale_model = ''
hypernetwork_name = ''
strength = ''
clip_vision_output = ''
conditioning_to = ''
conditioning_from = ''
conditioning_to_strength = ''
conditioning_1 = ''
conditioning_2 = ''
gligen_textbox_model = ''
text = ''
width = ''
height = ''
length = ''
x = ''
y = ''
stop_at_clip_layer = ''
set_cond_area = ''
default = ''
mask_bounds = ''
noise_augmentation = ''
start_percent = ''
end_percent = ''
grow_mask_by = ''
batch_index = ''
amount = ''
batch_size = ''
rotation = ''
none = ''
ninety_degrees = ''
oneeighty_degrees = ''
twoseventy_degrees = ''
flip_method = ''
x-axis_vertically = ''
y-axis_horizontally = ''
upscale_method = ''
crop = ''
scale_by = ''
samples_to = ''
samples_from = ''
feather = ''
destination = ''
source = ''
resize_source = ''
megapixels = ''
image1 = ''
image2 = ''
blend_factor = ''
blend_mode = ''
blur_radius = ''
sigma = ''
colors = ''
dither = ''
sharpen_radius = ''
alpha = ''
choose_file_to_upload = ''
left = ''
top = ''
right = ''
bottom = ''
feathering = ''
low_threshold = ''
high_threshold = ''
filename_prefix = ''
color = ''
channel = ''
connect_to_widget_input = ''
red = ''
green = ''
blue = ''
value = ''
operation = ''
expand = ''
tapered_corners = ''
ratio = ''
samples1 = ''
samples2 = ''
model_path = ''
config_name = ''
unet_name = ''
clip_name1 = ''
clip_name2 = ''
start = ''
end = ''
crop_w = ''
crop_h = ''
target_width = ''
target_height = ''
text_g = ''
text_l = ''
ascore = ''
model1 = ''
model2 = ''