# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[flows]
inputs = 'المدخلات'
outputs = 'مخرجات'
widgets = 'الحاجيات (الأدوات)'
	
[values]	
fixed = 'ثابت'
randomize = 'رتب عشوائيا'
increment = 'زيادة'
decrement = 'تناقص'
nearest-exact = 'أقرب دقيقة؟'
bilinear = 'ثنائي الخط'
area = 'مساحة'
bislerp = 'بسلرب'
bicubic = 'بيكوبيك'
enabled = 'تمكين'
disabled = 'المعاقون'
normal = 'عادي'
multiply = 'ضرب'
screen = 'شاشة'
overlay = 'تراكب'
soft_light = 'ضوء ناعم'
none = 'لا أحد'
floyd-steinberg = 'فلويد شتاينبرغ'
bayer-2 = 'باير-2'
bayer-4 = 'باير-4'
bayer-8 = 'باير-8'
bayer-16 = 'باير-16'
add = 'أضاف'
subtract = 'طرح'
and = 'و'
or = 'أو'
xor = 'Xor'
	
[types]	
model = 'نموذج'
clip = 'مشبك'
vae = 'Vae'
conditioning = 'تكييف'
positive = 'إيجابي'
negative = 'سلبي'
latent = 'كامن'
latent_image = 'صورة كامنة'
samples = 'عينات'
image = 'صورة'
seed = 'بذرة'
steps = 'خطوات'
cfg = 'سي إف جي'
sampler_name = 'اسم العينات'
scheduler = 'جدولة'
denoise = 'دينواز'
add_noise = 'أضف ضوضاء'
noise_seed = 'بذور الضوضاء'
control_after_generate = 'التحكم بعد التوليد'
return_with_leftover_noise = 'العودة مع بقايا الضوضاء'
start_at_step = 'ابدأ من الخطوة'
end_at_step = 'النهاية عند الخطوة'
ckpt_name = 'اسم ckpt'
vae_name = 'اسم vae'
pixels = 'بكسلات'
mask = 'قناع'
lora_name = 'اسم لورا'
strength_model = 'نموذج القوة'
strength_clip = 'مقطع القوة'
clip_name = 'اسم المقطع'
control_net = 'شبكة التحكم'
control_net_name = 'اسم شبكة التحكم'
clip_vision = 'رؤية القصاصة'
style_model = 'نموذج النمط'
style_model_name = 'قلم المدقة اسم الطراز'
gligen_name = 'اسم gligen'
gligen = 'غليجن'
model_name = 'اسم الطراز'
upscale_model = 'نموذج راقي'
hypernetwork_name = 'اسم الشبكة الفائقة'
strength = 'قوة'
clip_vision_output = 'مخرجات رؤية القصاصة'
conditioning_to = 'تكييف إلى'
conditioning_from = 'تكييف من'
conditioning_to_strength = 'تكييف للقوة'
conditioning_1 = 'تكييف 1'
conditioning_2 = 'تكييف 2'
gligen_textbox_model = 'نموذج gligen textbox'
text = 'نص'
width = 'عرض'
height = 'طول'
length = 'طول'
x = 'فلان'
y = 'ياء'
stop_at_clip_layer = 'توقف عند طبقة القصاصة'
set_cond_area = 'حدد منطقة كوند'
default = 'عجز عن السداد'
mask_bounds = 'حدود القناع'
noise_augmentation = 'زيادة الضوضاء'
start_percent = 'ابدأ النسبة المئوية'
end_percent = 'نهاية النسبة المئوية'
grow_mask_by = 'ينمو القناع بواسطة'
batch_index = 'مؤشر الدفعات'
amount = 'المبلغ'
batch_size = 'حجم الدفعة'
rotation = 'دوران'
none = 'لا أحد'
ninety_degrees = 'تسعون درجة'
oneeighty_degrees = 'ثمانين درجة'
twoseventy_degrees = 'درجتان وسبعون درجة'
flip_method = 'طريقة الوجه'
x-axis_vertically = 'المحور السيني عموديا'
y-axis_horizontally = 'المحور y أفقيا'
upscale_method = 'طريقة راقية'
crop = 'محصول'
scale_by = 'مقياس بواسطة'
samples_to = 'عينات إلى'
samples_from = 'عينات من'
feather = 'ريشة'
destination = 'وجهة'
source = 'مصدر'
resize_source = 'تغيير حجم المصدر'
megapixels = 'ميجابكسل'
image1 = 'صورة1'
image2 = 'صورة2'
blend_factor = 'عامل المزج'
blend_mode = 'وضع المزج'
blur_radius = 'دائرة نصف قطرها ضبابية'
sigma = 'سيجما'
colors = 'ألوان'
dither = 'تردد'
sharpen_radius = 'شحذ نصف القطر'
alpha = 'ألفا'
choose_file_to_upload = 'اختر ملفا لتحميله'
left = 'أيسر'
top = 'أعلى'
right = 'أيمن'
bottom = 'أسفل'
feathering = 'ريش'
low_threshold = 'عتبة منخفضة'
high_threshold = 'عتبة عالية'
filename_prefix = 'بادئة اسم الملف'
color = 'اللون'
channel = 'قناة'
connect_to_widget_input = 'الاتصال بإدخال القطعة الذكية'
red = 'أحمر'
green = 'أخضر'
blue = 'أزرق'
value = 'قيمة'
operation = 'تشغيل'
expand = 'وسع'
tapered_corners = 'زوايا مدببة'
ratio = 'نسبة'
samples1 = 'عينات1'
samples2 = 'عينات2'
model_path = 'مسار النموذج'
config_name = 'اسم التكوين'
unet_name = 'اسم unet'
clip_name1 = 'اسم المقطع1'
clip_name2 = 'اسم المقطع2'
start = 'بدأ'
end = 'نهاية'
crop_w = 'محصول ث'
crop_h = 'محصول ح'
target_width = 'العرض المستهدف'
target_height = 'الارتفاع المستهدف'
text_g = 'نص g'
text_l = 'نص l'
ascore = 'أسكور'
model1 = 'نموذج1'
model2 = 'نموذج2'
	