# %language% translations, courtesy of :
# %write_your_chosen_name_here%

[titles]
Note = 'Нота'
PrimitiveNode = 'Примитивный узел'
Reroute = 'Изменять, изменить маршрут/трассу'
Sampler = 'Вышивка'
SamplerAdvanced = 'Продвинутый пробоотборник'
CheckpointLoaderSimple = 'Простой загрузчик контрольных точек'
VAELoader = 'Погрузчик VAE'
LoraLoader = 'Лора Погрузчик'
ControlNetLoader = 'Загрузчик ControlNet'
DiffControlNetLoader = 'Загрузчик DiffControlNet'
StyleModelLoader = 'Стиль Загрузчик Модели'
CLIPVisionLoader = 'Загрузчик CLIP Vision'
unCLIPCheckpointLoader = 'Загрузчик контрольных точек unCLIP'
GLIGENLoader = 'Погрузчик GLIGEN'
UpscaleModelLoader = 'Высококлассный загрузчик моделей'
HypernetworkLoader = 'Гиперсетевой загрузчик'
StyleModelApply = 'Стиль Модель Применить'
GLIGENTextBoxApply = 'Применить текстовое поле GLIGEN'
CLIPTextEncode = 'Кодирование текста CLIP'
CLIPSetLastLayer = 'CLIP Установить последний слой'
ConditioningAverage = 'Среднее состояние'
ConditioningCombine = 'Кондиционный комбайн'
ConditioningConcat = 'Кондиционирование Concat'
ConditioningSetArea = 'Площадь задает кондиционирования'
ConditioningSetAreaPercentage = 'Процент площади набора кондиционирования'
ConditioningSetMask = 'Маска для кондиционирования'
CLIPVisionEncode = 'Кодирование CLIP Vision'
unCLIPConditioning = 'Кондиционирование unCLIP'
ControlNetApply = 'ControlNet Применить'
ControlNetApplyAdvanced = 'ControlNet Apply Advanced'
VAEEncodeForInpaint = 'Кодировка VAE Для Inpaint'
SetLatentNoiseMask = 'Установить скрытую шумовую маску'
LatentFromBatch = 'Скрытая От Партии'
RepeatLatentBatch = 'Повторить скрытый пакет'
RebatchLatents = 'Скрытая репакт'
LatentRotate = 'Скрытое вращение'
LatentFlip = 'Скрытый флип'
LatentCrop = 'Скрытая урожай'
VAEDecode = 'Декодирование VAE'
VAEEncode = 'Кодирование VAE'
EmptyLatentImage = 'Пустое скрытое изображение'
LatentUpscale = 'Скрытая высококлассная'
LatentUpscaleBy = 'Скрытая Высококлассная По'
LatentComposite = 'Скрытая композитная'
LatentCompositeMasked = 'Скрытая композитная маска'
ImageScale = 'Масштаб изображения'
ImageScaleBy = 'Масштаб Изображения По'
ImageUpscaleWithModel = 'Изображение в увеличенном масштабе с моделью'
ImageScaleToTotalPixels = 'Масштаб Изображения До Общего Количества Пикселей'
ImageBlend = 'Смешивание изображений'
ImageBlur = 'Размытие изображения'
ImageQuantize = 'Квантизация изображения'
ImageSharpen = 'Резкость изображения'
Canny = 'Хитрый, осторожный'
SaveImage = 'Сохранить изображение'
PreviewImage = 'Предварительный просмотр изображения'
LoadImage = 'Загрузить изображение'
ImageInvert = 'Инвертировать изображение'
ImageBatch = 'Пакет изображений'
ImagePadForOutpaint = 'Блокнот Для Изображений Для Outpaint'
EmptyImage = 'Пустое изображение'
ImageCompositeMasked = 'Композитное изображение в маске'
LoadImageMask = 'Загрузить маску изображения'
MaskToImage = 'Маска К Изображению'
ImageToMask = 'Изображение для маскировки'
ImageColorToMask = 'Цвет изображения для маски'
SolidMask = 'Твердая маска'
InvertMask = 'Инвертировать маску'
CropMask = 'Обрезка Маски'
MaskComposite = 'Композитная маска'
FeatherMask= 'Маска с перьями'
GrowMask = 'Расти маску'
VAEDecodeTiled = 'VAE Декодирование плитки'
VAEEncodeTiled = 'VAE Кодирование Плитка'
TomePatchModel = 'Модель Tome Patch'
SaveLatent = 'Сохранить скрытый'
LoadLatent = 'Скрытая загрузка'
LatentBlend = 'Скрытая смесь'
DiffusersLoader = 'Диффузоры Загрузчик'
CLIPLoader = 'Загрузчик CLIP'
CheckpointLoader = 'Загрузчик контрольных точек'
UNETLoader = 'Загрузчик UNET'
DualCLIPLoader = 'Двойной загрузчик CLIP'
ConditioningZeroOut = 'Обусловливающий Нулевой Выход'
ConditioningSetTimestepRange = 'Кондиционирование Установить Диапазон Временных Шагов'
CLIPTextEncodeSDXL = 'Кодировка текста CLIP SDXL'
CLIPTextEncodeSDXLRefiner = 'Кодировка текста CLIP SDXL Refiner'
ModelMergeSimple = 'Простое слияние моделей'
ModelMergeBlocs = 'Блоки слияния моделей'
CheckpointSave = 'Контрольная точка Сохранить'
CLIPMergeSimple = 'Простое слияние CLIP'
ModelMergeBlockNumber = 'Номер блока слияния модели'
ModelMergeSDXL = 'Слияние моделей SDXL'
ModelMergeSDXLTransformers = 'Модель слияния трансформаторов SDXL'
ModelMergeSDXLDetailedTransformers = 'Модель Слияние детализированные трансформаторы SDXL'